-- 01_create_tables.sql
-- A executer dans Supabase > SQL Editor.

create table if not exists public.correspondance (
    id bigint generated by default as identity primary key,
    activite_ds text not null,
    groupe_articles text,
    secteur text,
    source_ligne integer,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint correspondance_activite_groupe_unique unique (activite_ds, groupe_articles)
);

create index if not exists idx_correspondance_activite_ds
    on public.correspondance (activite_ds);
create index if not exists idx_correspondance_groupe_articles
    on public.correspondance (groupe_articles);
create index if not exists idx_correspondance_secteur
    on public.correspondance (secteur);

create table if not exists public.ds_code_barre (
    id bigint generated by default as identity primary key,
    ref_ds text not null,
    ref_fournisseur text,
    libelle_source text,
    groupe_articles text,
    code_remise text,
    code_barre text not null,
    type_code_barre text not null,
    source_ligne integer,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ds_code_barre_type_check
        check (type_code_barre in ('EAN13', 'CODE128', 'CODE39')),
    constraint ds_code_barre_combinaison_unique
        unique (ref_ds, code_barre, type_code_barre)
);

create index if not exists idx_ds_code_barre_ref_ds
    on public.ds_code_barre (ref_ds);
create index if not exists idx_ds_code_barre_code_barre
    on public.ds_code_barre (code_barre);
create index if not exists idx_ds_code_barre_groupe_articles
    on public.ds_code_barre (groupe_articles);

-- Les donnees sont lues par l'API serveur avec la cle service_role.
-- Aucun acces direct anonyme n'est necessaire.
alter table public.correspondance enable row level security;
alter table public.ds_code_barre enable row level security;
